name: Tom CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  test:

    runs-on: macos-latest
    
    env:
      XC_VERSION: ${{ '12.4' }}
      XC_WORKSPACE: ${{ 'Example/Tom.xcworkspace' }}
      XC_SCHEME: ${{ 'Tom-Example' }}
      
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Run Unit and UI Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
